site_name: UCSD CSE Fellows 2021

nav:
    - Program: index.md
    - Apply: apply.md
    - Deadlines: deadlines.md

theme: spacelab

markdown_extensions:
    - toc:
        permalink: true

plugins:
    - encryptcontent:
        global_password: 'jolly_good_fellows'
